name: .NET CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - run: dotnet restore SpaceBattle.sln
      - run: dotnet build SpaceBattle.sln --no-restore --configuration Release
      - run: dotnet test SpaceBattle.sln --no-build --configuration Release --collect:"XPlat Code Coverage"
      